### ISSUE TITLE
File link in notifications seems to not work

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#5227]
### Steps to reproduce
[enable notification app]
[as Brian disable auto-accept-share]
1. Create users `Alice` and `Brian`
2. Login as `Alice`, create folder `TOSHARE` and share it with `Brian`
3. Login as `Brian`, follow the link from notifications dropdown

### Actual behaviour
![noti01](https://user-images.githubusercontent.com/52366632/121463236-67b20580-c9d1-11eb-967f-79e15c461c42.png)
![noti02](https://user-images.githubusercontent.com/52366632/121463241-6bde2300-c9d1-11eb-8e4d-ecdfa0933f5f.png)

### Server configuration
**Operating system**: `Ubuntu 20.04`
**Web server:** `Apache`
**Database:** `MySQL`
**PHP version:** `7.4`

**ownCloud version:** `10.8.0 prealpha (git)`

**Comment by individual-it** [comment]
is that the case for all private links for you or just when you navigate from the notification?

**Comment by pascalwengerter** [comment]
Could you please re-try with the latest web `master`? We merged a big PR today and I remember fixing the tests for this the other day and just tried myself, see screenshot below:

<img width="426" alt="Screenshot 2021-06-10 at 20 53 37" src="https://user-images.githubusercontent.com/16822008/121588540-efc5f880-ca2d-11eb-98e5-ce35ba869844.png">

**Comment by saw-jan** [comment]
I still get the same link with latest web and latest core
![sharenoti](https://user-images.githubusercontent.com/52366632/122157458-9b39d780-ce8a-11eb-82f2-7e93f7117723.png)

oC10 running on: `http://localhost/core`
web: `http://localhost:9100`

**Comment by individual-it** [comment]
@saw-jan can you paste your core configuration (output of `sudo -u www-data ./occ config:list`)

**Comment by saw-jan** [comment]
Yeah,
```json
{
    "system": {
        "instanceid": "ocjhxqg8fllg",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "172.17.0.1"
        ],
        "datadirectory": "\/mnt\/sda1\/www\/core\/data",
        "overwrite.cli.url": "http:\/\/localhost\/core",
        "dbtype": "mysql",
        "version": "10.8.0.0",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "apps_paths": [
            {
                "path": "\/mnt\/sda1\/www\/core\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/mnt\/sda1\/www\/core\/apps-external",
                "url": "\/apps-external",
                "writable": true
            }
        ],
        "installed": true,
        "htaccess.RewriteBase": "\/core\/",
        "csrf.disabled": true,
        "enable_previews": false,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "cors.allowed-domains": [
            "http:\/\/localhost:9100"
        ],
        "log_type": "owncloud",
        "web.rewriteLinks": true,
        "web.baseUrl": "http:\/\/localhost:9100"
    },
    "apps": {
        "backgroundjob": {
            "lastjob": "650"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging,dav"
        },
        "core": {
            "first_install_version": "10.7.1.0",
            "installedat": "1621333013.807",
            "lastcron": "1623817736",
            "lastupdateResult": "[]",
            "lastupdatedat": "1623816746",
            "oc.integritycheck.checker": "{\"notifications\":{\"EXCEPTION\":{\"class\":\"OC\\\\IntegrityCheck\\\\Exceptions\\\\MissingSignatureException\",\"message\":\"Signature data not found.\"}},\"systemtags\":{\"EXCEPTION\":{\"class\":\"OC\\\\IntegrityCheck\\\\Exceptions\\\\MissingSignatureException\",\"message\":\"Signature data not found.\"}},\"oauth2\":{\"EXCEPTION\":{\"class\":\"OC\\\\IntegrityCheck\\\\Exceptions\\\\MissingSignatureException\",\"message\":\"Signature data not found.\"}},\"comments\":{\"EXCEPTION\":{\"class\":\"OC\\\\IntegrityCheck\\\\Exceptions\\\\MissingSignatureException\",\"message\":\"Signature data not found.\"}},\"testing\":{\"EXCEPTION\":{\"class\":\"OC\\\\IntegrityCheck\\\\Exceptions\\\\MissingSignatureException\",\"message\":\"Signature data not found.\"}}}",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "shareapi_allow_group_sharing": "yes",
            "shareapi_allow_links": "yes",
            "shareapi_allow_mail_notification": "no",
            "shareapi_allow_public_notification": "no",
            "shareapi_allow_public_upload": "yes",
            "shareapi_allow_resharing": "yes",
            "shareapi_allow_share_dialog_user_enumeration": "yes",
            "shareapi_allow_social_share": "yes",
            "shareapi_auto_accept_share": "yes",
            "shareapi_default_expire_date": "no",
            "shareapi_default_expire_date_group_share": "no",
            "shareapi_default_expire_date_remote_share": "no",
            "shareapi_default_expire_date_user_share": "no",
            "shareapi_enabled": "yes",
            "shareapi_enforce_expire_date": "no",
            "shareapi_enforce_expire_date_group_share": "no",
            "shareapi_enforce_expire_date_remote_share": "no",
            "shareapi_enforce_expire_date_user_share": "no",
            "shareapi_enforce_links_password_read_only": "no",
            "shareapi_enforce_links_password_read_write": "no",
            "shareapi_enforce_links_password_write_only": "no",
            "shareapi_exclude_groups": "no",
            "shareapi_exclude_groups_list": "",
            "shareapi_only_share_with_group_members": "no",
            "shareapi_only_share_with_membership_groups": "no",
            "shareapi_share_dialog_user_enumeration_group_members": "no",
            "vendor": "owncloud"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "0.6.0",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "0.5.0",
            "types": "filesystem"
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.5.2",
            "types": "filesystem"
        },
        "files_external": {
            "enabled": "yes",
            "installed_version": "0.8.0",
            "types": "filesystem"
        },
        "files_sharing": {
            "blacklisted_receiver_groups": "[]",
            "enabled": "yes",
            "incoming_server2server_share_enabled": "yes",
            "installed_version": "0.14.0",
            "outgoing_server2server_share_enabled": "yes",
            "types": "filesystem"
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "0.9.1",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "0.5.2",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "0.5.0",
            "types": "authentication"
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "0.5.0",
            "types": "prevent_group_restriction"
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "testing": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": "dav,authentication"
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "0.2.1",
            "types": ""
        }
    }
}

```

**Comment by saw-jan** [comment]
> is that the case for all private links for you or just when you navigate from the notification?

private links are as 
![pvtlinks](https://user-images.githubusercontent.com/52366632/122158135-d557a900-ce8b-11eb-8cae-028fd316ced1.png)

**Comment by saw-jan** [comment]
core/config/config.php
```php
...
  'htaccess.RewriteBase' => '/core/',
  'web.rewriteLinks' => true,
  'web.baseUrl' => 'http://localhost:9100',
...
```

**Comment by kulmann** [comment]
I was able to reproduce this. It seems like the window url is used as base url for the private link. It needs to use the server url instead.
But, while looking into this with @dschmidt  we discussed that it doesn't make much sense to show the private link at all. The user doesn't have access to the resource. Only way to gain access is to accept the share. In that case the notification disappears anyway.
I'd accept removing the private link from the notification as a solution to this issue.
